import zipfile
import json
from pathlib import Path
from typing import Set

CATEGORY_MAP = {
    "Textures": ["textures/"],
    "Models": ["models/"],
    "Blockstates": ["blockstates/"],
    "Sounds": ["sounds/", "sounds.json"],
    "Fonts": ["font/"],
    "Language Files": ["lang/"],
    "Particles": ["particles/"],
    "Shaders": ["shaders/"],
    "Atlases": ["atlases/"]
}

def extract_filtered_pack(zip_path: Path, dest_dir: Path, selected_categories: Set[str]) -> None:
    dest_dir.mkdir(parents=True, exist_ok=True)
    
    with zipfile.ZipFile(zip_path, 'r') as zf:
        # Find root prefix. Usually the first directory, e.g. "minecraft-assets-1.21.11/"
        root_prefix = ""
        for name in zf.namelist():
            if "/assets/minecraft/" in name:
                root_prefix = name[:name.index("/assets/minecraft/") + 1]
                break
        
        has_pack_mcmeta = False
        
        for name in zf.namelist():
            if name.endswith("/"):
                continue
                
            if not name.startswith(root_prefix):
                continue
                
            rel_name = name[len(root_prefix):] # e.g. "assets/minecraft/textures/block/stone.png" or "pack.mcmeta"
            
            # Check pack files. Sometimes they are at the root, sometimes inside assets/
            if rel_name in ("pack.mcmeta", "pack.png", "assets/pack.mcmeta", "assets/pack.png"):
                if "pack.mcmeta" in rel_name:
                    has_pack_mcmeta = True
                _extract_file(zf, name, dest_dir / Path(rel_name).name)
                continue
                
            # Filter assets
            if rel_name.startswith("assets/minecraft/"):
                sub_path = rel_name[len("assets/minecraft/"):] # e.g. "textures/block/stone.png"
                
                # Check which category it belongs to
                matched_category = None
                for cat, paths in CATEGORY_MAP.items():
                    for p in paths:
                        if sub_path == p or sub_path.startswith(p):
                            matched_category = cat
                            break
                    if matched_category:
                        break
                        
                if not matched_category:
                    matched_category = "Other Resource-Pack Assets"
                    
                if matched_category in selected_categories:
                    _extract_file(zf, name, dest_dir / rel_name)
                    
        # If no pack.mcmeta was found, generate a basic one
        if not has_pack_mcmeta:
            pack_mcmeta_path = dest_dir / "pack.mcmeta"
            with open(pack_mcmeta_path, "w", encoding="utf-8") as f:
                json.dump({
                    "pack": {
                        "pack_format": 1,
                        "description": "Generated by Asset Install"
                    }
                }, f, indent=2)

def _extract_file(zf: zipfile.ZipFile, zip_name: str, dest_path: Path):
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    with zf.open(zip_name) as source, open(dest_path, "wb") as target:
        target.write(source.read())
