import zipfile
import io
import json
from pathlib import Path
from asset_install.extractor import extract_filtered_pack

def test_extract_filtered_pack(tmp_path):
    # Create mock zip file
    zip_path = tmp_path / "mock.zip"
    dest_dir = tmp_path / "filtered_pack"
    
    with zipfile.ZipFile(zip_path, "w") as zf:
        # Mock repository structure
        zf.writestr("minecraft-assets-1.21/assets/pack.mcmeta", '{"pack": {"pack_format": 1}}')
        zf.writestr("minecraft-assets-1.21/assets/minecraft/textures/block/stone.png", b"stone")
        zf.writestr("minecraft-assets-1.21/assets/minecraft/sounds/ambient/cave.ogg", b"cave")
        zf.writestr("minecraft-assets-1.21/assets/minecraft/sounds.json", b"sounds")
        zf.writestr("minecraft-assets-1.21/assets/minecraft/font/default.json", b"font")
        zf.writestr("minecraft-assets-1.21/assets/minecraft/unknown_thing/file.txt", b"unknown")
        
    # Extract only Textures and Sounds
    extract_filtered_pack(zip_path, dest_dir, {"Textures", "Sounds"})
    
    # Check structure
    assert (dest_dir / "pack.mcmeta").exists()
    assert (dest_dir / "pack.mcmeta").read_text() == '{"pack": {"pack_format": 1}}'
    
    assert (dest_dir / "assets/minecraft/textures/block/stone.png").exists()
    assert (dest_dir / "assets/minecraft/sounds/ambient/cave.ogg").exists()
    assert (dest_dir / "assets/minecraft/sounds.json").exists()
    
    # Unselected categories should not exist
    assert not (dest_dir / "assets/minecraft/font/default.json").exists()
    assert not (dest_dir / "assets/minecraft/unknown_thing/file.txt").exists()

def test_extract_fallback_mcmeta(tmp_path):
    # Create mock zip without pack.mcmeta
    zip_path = tmp_path / "mock2.zip"
    dest_dir = tmp_path / "filtered_pack2"
    
    with zipfile.ZipFile(zip_path, "w") as zf:
        zf.writestr("minecraft-assets-1.21/assets/minecraft/textures/block/stone.png", b"stone")
        
    extract_filtered_pack(zip_path, dest_dir, {"Textures"})
    
    # Check fallback mcmeta generated
    assert (dest_dir / "pack.mcmeta").exists()
    data = json.loads((dest_dir / "pack.mcmeta").read_text())
    assert data["pack"]["description"] == "Generated by Asset Install"
